package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: generate <source-directory> <output-file>")
		os.Exit(2)
	}
	sourceRoot, outputPath := os.Args[1], os.Args[2]
	var paths []string
	err := filepath.WalkDir(sourceRoot, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		relative, err := filepath.Rel(sourceRoot, path)
		if err != nil {
			return err
		}
		paths = append(paths, filepath.ToSlash(relative))
		return nil
	})
	if err != nil {
		fatal(err)
	}
	sort.Strings(paths)

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage agentskills\n\nvar bundledSkillFiles = map[string][]byte{\n")
	for _, relative := range paths {
		data, err := os.ReadFile(filepath.Join(sourceRoot, filepath.FromSlash(relative)))
		if err != nil {
			fatal(err)
		}
		fmt.Fprintf(&output, "\t%s: []byte(%s),\n", strconv.Quote(relative), strconv.Quote(string(data)))
	}
	output.WriteString("}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
